[package]
name = "sqlite"
version = "0.1.0"
alya-version = "0.0.13"
entry = "src/lib.alya"
description = "Fast and lightweight SQLite3 bindings for Alya"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/sqlite"
keywords = ["alya", "alya-lang", "package", "sqlite", "database", "sql", "sqlite3", "storage"]

[dependencies]

[build]
c-sources = ["c/sqlite3.c"]
c-flags = ["-O2", "-DSQLITE_THREADSAFE=0", "-DSQLITE_OMIT_LOAD_EXTENSION"]
c-include-dirs = ["c"]
